// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReAddressListDao is internal type for wrapping internal DAO implements.
type internalReAddressListDao = *internal.ReAddressListDao

// reAddressListDao is the data access object for table re_address_list.
// You can define custom methods on it to extend its functionality as you wish.
type reAddressListDao struct {
	internalReAddressListDao
}

var (
	// ReAddressList is globally public accessible object for table re_address_list operations.
	ReAddressList = reAddressListDao{
		internal.NewReAddressListDao(),
	}
)

// Fill with you ideas below.
