// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReAdminUserDao is internal type for wrapping internal DAO implements.
type internalReAdminUserDao = *internal.ReAdminUserDao

// reAdminUserDao is the data access object for table re_admin_user.
// You can define custom methods on it to extend its functionality as you wish.
type reAdminUserDao struct {
	internalReAdminUserDao
}

var (
	// ReAdminUser is globally public accessible object for table re_admin_user operations.
	ReAdminUser = reAdminUserDao{
		internal.NewReAdminUserDao(),
	}
)

// Fill with you ideas below.
