// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReAboutDao is internal type for wrapping internal DAO implements.
type internalReAboutDao = *internal.ReAboutDao

// reAboutDao is the data access object for table re_about.
// You can define custom methods on it to extend its functionality as you wish.
type reAboutDao struct {
	internalReAboutDao
}

var (
	// ReAbout is globally public accessible object for table re_about operations.
	ReAbout = reAboutDao{
		internal.NewReAboutDao(),
	}
)

// Fill with you ideas below.
