// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReOrderListDao is internal type for wrapping internal DAO implements.
type internalReOrderListDao = *internal.ReOrderListDao

// reOrderListDao is the data access object for table re_order_list.
// You can define custom methods on it to extend its functionality as you wish.
type reOrderListDao struct {
	internalReOrderListDao
}

var (
	// ReOrderList is globally public accessible object for table re_order_list operations.
	ReOrderList = reOrderListDao{
		internal.NewReOrderListDao(),
	}
)

// Fill with you ideas below.
