// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReProtocolDao is internal type for wrapping internal DAO implements.
type internalReProtocolDao = *internal.ReProtocolDao

// reProtocolDao is the data access object for table re_protocol.
// You can define custom methods on it to extend its functionality as you wish.
type reProtocolDao struct {
	internalReProtocolDao
}

var (
	// ReProtocol is globally public accessible object for table re_protocol operations.
	ReProtocol = reProtocolDao{
		internal.NewReProtocolDao(),
	}
)

// Fill with you ideas below.
