// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReQuestionDao is internal type for wrapping internal DAO implements.
type internalReQuestionDao = *internal.ReQuestionDao

// reQuestionDao is the data access object for table re_question.
// You can define custom methods on it to extend its functionality as you wish.
type reQuestionDao struct {
	internalReQuestionDao
}

var (
	// ReQuestion is globally public accessible object for table re_question operations.
	ReQuestion = reQuestionDao{
		internal.NewReQuestionDao(),
	}
)

// Fill with you ideas below.
