// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReRegionsDao is internal type for wrapping internal DAO implements.
type internalReRegionsDao = *internal.ReRegionsDao

// reRegionsDao is the data access object for table re_regions.
// You can define custom methods on it to extend its functionality as you wish.
type reRegionsDao struct {
	internalReRegionsDao
}

var (
	// ReRegions is globally public accessible object for table re_regions operations.
	ReRegions = reRegionsDao{
		internal.NewReRegionsDao(),
	}
)

// Fill with you ideas below.
