// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReSettingDao is internal type for wrapping internal DAO implements.
type internalReSettingDao = *internal.ReSettingDao

// reSettingDao is the data access object for table re_setting.
// You can define custom methods on it to extend its functionality as you wish.
type reSettingDao struct {
	internalReSettingDao
}

var (
	// ReSetting is globally public accessible object for table re_setting operations.
	ReSetting = reSettingDao{
		internal.NewReSettingDao(),
	}
)

// Fill with you ideas below.
