// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReTakeListDao is internal type for wrapping internal DAO implements.
type internalReTakeListDao = *internal.ReTakeListDao

// reTakeListDao is the data access object for table re_take_list.
// You can define custom methods on it to extend its functionality as you wish.
type reTakeListDao struct {
	internalReTakeListDao
}

var (
	// ReTakeList is globally public accessible object for table re_take_list operations.
	ReTakeList = reTakeListDao{
		internal.NewReTakeListDao(),
	}
)

// Fill with you ideas below.
