// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"GF_Recovery/internal/dao/internal"
)

// internalReUserDao is internal type for wrapping internal DAO implements.
type internalReUserDao = *internal.ReUserDao

// reUserDao is the data access object for table re_user.
// You can define custom methods on it to extend its functionality as you wish.
type reUserDao struct {
	internalReUserDao
}

var (
	// ReUser is globally public accessible object for table re_user operations.
	ReUser = reUserDao{
		internal.NewReUserDao(),
	}
)

// Fill with you ideas below.
